//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PPPprojekat
{
    using System;
    using System.Collections.Generic;
    
    public partial class Prodavnica
    {
        public Nullable<int> IdUnosa { get; set; }
        public Nullable<int> Stanje { get; set; }
        public int RedniBroj { get; set; }
    
        public virtual UnosUProdavnicu UnosUProdavnicu { get; set; }
    }
}
