//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PPPprojekat
{
    using System;
    using System.Collections.Generic;
    
    public partial class UnosUProdavnicu
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public UnosUProdavnicu()
        {
            this.Prodavnica = new HashSet<Prodavnica>();
        }
    
        public int IdUnosa { get; set; }
        public Nullable<int> BarKodArtikla { get; set; }
        public Nullable<int> Kolicina { get; set; }
        public Nullable<System.DateTime> Datum { get; set; }
        public Nullable<System.TimeSpan> Vreme { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Prodavnica> Prodavnica { get; set; }
        public virtual Proizvod Proizvod { get; set; }
    }
}
